Feature/howard duplicate hit filter tool updated -- reissuing
PandoraPFA/larpandora pull request #29
Opened 2023-03-15 16:31 UTC by brucehoward-physics

Copying from previous PR:

The intent of this PR is to turn the usage of CollectHits in LArPandora.cxx into an art tool to allow one to do some customization at this stage of input. For example, with this we would plan to have a tool living in icaruscode that basically copies CollectHits but does some filtering while inputting the hits. The default functionality here is intended to effectively preserve previous behavior.

Appreciate eyes on the intended changes. I spotted a few comments and things we probably want to remove before merging, but in any case making the PR now to get people looking at it...

A question: in putting together the art tool, I took some inspiration and guidance from other code. Do we want to actually specify a destructor here? I noticed IShowerTool does, for example, but wasn't sure.

2023-03-16 08:52 UTC, AndyChappell requested changes
Thanks Bruce. I think the logic here looks sound, I'm just trying to get this checked through the high stats CI at the moment, but in the interim I've suggested a few fairly superficial changes.

2023-03-16 08:52 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionTool.h
> +namespace HitCollectionTools {
I think the namespace here should probably still be lar_pandora.

2023-03-16 08:52 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionToolDefault_tool.cc
> +/**
I think the _tool suffix can be dropped from the name here and the source file extension should be cxx for consistency with the other larpandora classes. I think this should also be separated into a source and header file to split declarations and definitions.

2023-03-16 08:52 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionToolDefault_tool.cc
> +namespace HitCollectionTools {
As previously, namespace lar_pandora

2023-03-16 08:52 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionToolDefault_tool.cc
> +    lar_pandora::LArPandoraHelper::CollectHits(evt, label, hitVector);
Won't need the lar_pandora namespace specifcation if the namespace is changed.

2023-03-16 08:52 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionTool.h
> +  class HitCollectionTool
Probably want to call this IHitCollectionTool in keeping with other pure interfaces in larpandora.

2023-03-16 21:33 UTC, brucehoward-physics commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionToolDefault_tool.cc
> +/**
Are you sure I can drop this and it's not required by the art tool?

2023-03-16 23:29 UTC, brucehoward-physics commented
Because I was working in a different version than this rebased one, I made edits there and cherry-picked the commit over to this branch. Hopefully that works fine?

Anyway, I tried to address most of the stuff, please let me know if the result is not satisfactory.

For one of the comments I have a follow-up question (about the "_tool.cc" vs. ".cxx")

2023-03-17 08:59 UTC, AndyChappell commented on larpandora/LArPandoraInterface/LArPandoraHitCollectionToolDefault_tool.cc
> +/**
Ah ok, if it's an art requirement then you can ignore my comment.

2023-03-20 07:51 UTC, AndyChappell approved these changes

2023-03-20 07:52 UTC, merged